### ISSUE TITLE
Samtools requirement 

### ISSUE THREAD

**Issue by ekelley903** [RabadanLab/arcasHLA#14]
Encountered a problem using the recommended version of samtools 1.19.  Updated to version 1.3.1 and tool ran successfully.

**Comment by IoanFilip2** [comment]
Great, thanks for the information! What was the problem, how was it related to arcasHLA?

**Comment by ekelley903** [comment]
The arcasHLA README says to use version 1.19 of samtools, however it won't successfully run with that version.  I used version 1.3.1 and it worked.

**Comment by IoanFilip2** [comment]
Ok thanks for clarifying. We had arcasHLA tested with samtools 1.19, but the requirement should likely say samtools 1.19 or newer (although we have not tested it with every version between 1.19 and the newest). It's possible that arcasHLA failed with samtools 1.19 in your system configuration due to many other possible factors. Glad it works well with 1.3.1!
