### ISSUE TITLE
question about flag --unmapped behavior

### ISSUE THREAD

**Issue by jfx319** [RabadanLab/arcasHLA#26]
According to the sample.extract.log, the `extract --unmapped --paired` appears to be using:
```
samtools view -f 12 sample.bam 6
```
Indeed this appears to be the way the command is [constructed](https://github.com/RabadanLab/arcasHLA/blob/48817526f3e9f0c6e5867ef1db250a8dc7e95905/scripts/extract.py#L101).

1. Why require a region of chromosome 6 in the case of both unmapped reads? Naively, this seems contradictory (an unmapped read shouldn't have a chromosome, right?). I tested this separately on my bam and this exact filter scheme actually causes the output to be empty. In contrast, removing the chr 6 region requirement shows output with both reads unmapped and the chromosome as "*". Would any reads ever be marked as unmapped and to chr6, or is it an impossible to satisfy filter? 

2. Why require both reads to be unmapped (the bitwise 12)? What about cases where one read is mapped to chr6 while the other is unmapped?

3. I have not checked the logic for single-end input

These may be worth clarifying in the manual/readme so the user is aware for these situations.

```
time samtools view -@8 -f 12 sample.bam 6 > sample.hla.chr6.bothunmapped.sam &
time samtools view -@8 -f 12 sample.bam > sample.hla.any.bothunmapped.sam &
time samtools view -@8 -f 12 sample.bam '*' > sample.hla.asterisk.bothunmapped.sam &
```
- The first one is relatively fast, but finds nothing.
- The second one is slow (probably reads through the whole bam), and outputs a 15GB SAM.
- The third one is fast (but assumes unmapped entries are to chr '*'), and the md5sum of the output agrees with the second.

**Comment by IoanFilip2** [comment]
Thanks for bringing out this issue. As written in the current version, this appears to be a bug, which will be corrected shortly in a new update. The intended inclusion of un-mapped reads (even for at least one mate if pair-end) is to capture possibly "lost" reads in the alignment step (that are possibly excluded due to extensive multimapping in the HLA locus, for example) but that should still be included in the arcasHLA genotyping step for resolving the correct HLA alleles. Thank your additionally for tests that you performed. The intended usage should be the same samtools command (as on line 101 of extract.py script) but without extension by "chrom" (the extension command should only have the bam file path and the appending to hla_filtered). There is one issue, as you pointed out, with including all the unmapped reads, depending on the tissue of origin of the sample, namely abundant unmapped reads; so this flag, while optional, should be used with caution in some contexts.
