### ISSUE TITLE
pseudoalign call to analyze_reads not gathering correct info for kallisto

### ISSUE THREAD

**Issue by alexvpickering** [RabadanLab/arcasHLA#43]
relevant code: https://github.com/RabadanLab/arcasHLA/blob/a1383830e302126c6e41630e71733e4b315e1ca7/scripts/align.py#L95

Here is the docs sections from kallisto regarding single-ended reads and the `-l` and `-s` flags:

> In the case of single-end reads, the **-l option must be used to specify the average fragment length**. Typical Illumina libraries produce fragment lengths ranging from 180–200 bp but it’s best to determine this from a library quantification with an instrument such as an Agilent Bioanalyzer.

Note that `analyze_reads` is determining the _read_ lengths/sds, not the _fragment_ lengths/sds (which must be determined experimentally e.g. using an Agilent Bioanalyzer). Read length is related to the number of cycles on the sequencer and so my expectation is that using the read length standard deviation implies much less variation than is true (in fact the current code for `arcasHLA`  prevents `-s 0` which happens because you are using read length). Also read length and fragment length can and often do differ substantially. 

 I would suggest exposing these arguments to the `arcasHLA` call, setting the default to `-l 200 -s 20`, and warning the user if the defaults are used. These defaults or similar are also used in a few other repos ([Curse](http://bioinformatics.psb.ugent.be/webtools/Curse/util/Prose_manual.pdf), [drugseqr](https://github.com/hms-dbmi/drugseqr) - personal repo, [salmon](https://github.com/COMBINE-lab/salmon/blob/642dc19028d9697bc69ddcde1db76b5bbba24ff5/include/SalmonDefaults.hpp#L58)) and similar suggestions have been made [elsewhere](https://www.biostars.org/p/252823/). I've submitted a PR if you are interested. 

One advantage is the time and memory usage is dramatically reduced. Might be nice to redo the analysis you presented in your paper to make sure it doesn't substantially change things. Thank you for the great package!

**Comment by IoanFilip2** [comment]
Thank you for your interest in our tool, and for this informative post. The observation is correct: what is required is the fragment length/std and not the read length, which is what we are supplying for single-end reads. That is an error, and fixing it could also improve performance due to omitting the running of analyze_reads(...). However, it appears that fragment length information is only used in kallisto quantification to account for sequence-specific biases as a result of nonrandom priming of fragments (see kallisto paper). In fact, we have our own quantification step in arcasHLA that does not directly use kallisto quant. Additionally, in kallisto quantification step, the mean/std are only used to generate weights from a Gaussian distribution with these specified parameters. We expect the impact of using mean/std of reads as opposed to mean/std of fragments to be minimal, if none at all, on our results.
