### ISSUE TITLE
Allow file names with "." in the name

### ISSUE THREAD

**Issue by jen-dfci** [RabadanLab/arcasHLA#68]
We would like to process samples with arcasHLA, but need to use file names with a "." which causes an error.  Example file names include "AABGIOKSQ.01". Would you be able to update arcasHLA's code to handle these filenames?

**Comment by jen-dfci** [comment]
Please see pull request submitted 7/19/21

**Comment by tpereachamblee** [comment]
Thank you for using our tool. You're correct, arcasHLA presently does not support filenames with "." appearing before the file extension. This a reasonable convention to adhere to since, typically, we regard everything after the first "." as a file's extension (consider multi-part extensions such as ".tar.gz"). That said, we may update this in a future release.
